### ISSUE TITLE
Future of open-i18n

### ISSUE THREAD

**Issue by zbraniecki** [i18n-concept/rust-discuss#1]
Let's kick off with the discussion on what do we want to do with https://github.com/open-i18n

It covers some of the ICU, in particular:

-   [`unic-char`](unic/char/): Unicode Character Tools.
    [![Crates.io](https://img.shields.io/crates/v/unic-char.svg)](https://crates.io/crates/unic-char/)

-   [`unic-ucd`](unic/ucd/): Unicode Character Database
    ([UAX\#44](https://unicode.org/reports/tr44/)).
    [![Crates.io](https://img.shields.io/crates/v/unic-ucd.svg)](https://crates.io/crates/unic-ucd/)

-   [`unic-bidi`](unic/bidi/): Unicode Bidirectional Algorithm
    ([UAX\#9](https://unicode.org/reports/tr9/)).
    [![Crates.io](https://img.shields.io/crates/v/unic-bidi.svg)](https://crates.io/crates/unic-bidi/)

-   [`unic-normal`](unic/normal/): Unicode Normalization Forms
    ([UAX\#15](https://unicode.org/reports/tr15/)).
    [![Crates.io](https://img.shields.io/crates/v/unic-normal.svg)](https://crates.io/crates/unic-normal/)

-   [`unic-segment`](unic/segment/): Unicode Text Segmentation Algorithms
    ([UAX\#29](https://unicode.org/reports/tr29/)).
    [![Crates.io](https://img.shields.io/crates/v/unic-segment.svg)](https://crates.io/crates/unic-segment/)

-   [`unic-idna`](unic/idna/): Unicode IDNA Compatibility Processing
    ([UTS\#46](https://unicode.org/reports/tr46/)).
    [![Crates.io](https://img.shields.io/crates/v/unic-idna.svg)](https://crates.io/crates/unic-idna/)

-   [`unic-emoji`](unic/emoji/): Unicode Emoji
    ([UTS\#51](https://unicode.org/reports/tr51/)).
    [![Crates.io](https://img.shields.io/crates/v/unic-emoji.svg)](https://crates.io/crates/unic-emoji/)

I'm not sure how up to date those are to ICU 65 and well maintained. My impression was that Behnam is looking to grow the maintainers group and/or hand them over, but I'm not sure if they should be merged together with crates such as `unic-langid` or `intl_pluralrules` or some future date time format, or is it ok to keep the unicode characters crates separate from the higher level intl formatting and locale management.

Thoughts?

**Comment by behnam** [comment]
Few notes heres:

- My plans for open-i18n, the org, is to provide more open-source i18n data for the community. It's not limited to UNIC, but was going to use some of that data in UNIC.

- My focus on UNIC has been around text processing, and dev tooling. I have plans to add more around that to UNIC. This is the main reason that the crates listed above are forked.

- Agreed that could be a better approach to keep the L10n data parts separate from the non-L10n parts.

**Comment by zbraniecki** [comment]
[`unicode-rs`](https://github.com/unicode-rs) covers similar scope and recently got updated to Unicode 11:

-   [`unicode-segmentation`](https://github.com/unicode-rs/unicode-segmentation): Grapheme Cluster and Word boundaries according to UAX#29 rules.
    [![Crates.io](https://img.shields.io/crates/v/unicode-segmentation.svg)](https://crates.io/crates/unicode-segmentation/)

-   [`unicode-normalization`](https://github.com/unicode-rs/unicode-normalization): Unicode Normalization forms according to UAX#15 rules.
    [![Crates.io](https://img.shields.io/crates/v/unicode-normalization.svg)](https://crates.io/crates/unicode-normalization/)

-   [`unicode-xid`](https://github.com/unicode-rs/unicode-xid): Determine if a char is a valid identifier for a parser and/or lexer according to Unicode Standard Annex #31 rules.
    [![Crates.io](https://img.shields.io/crates/v/unicode-xid.svg)](https://crates.io/crates/unicode-xid/)

-   [`unicode-width`](https://github.com/unicode-rs/unicode-width): Displayed width of Unicode characters and strings according to UAX#11 rules.
    [![Crates.io](https://img.shields.io/crates/v/unicode-width.svg)](https://crates.io/crates/unicode-width/)

**Comment by zbraniecki** [comment]
I think it would be good to verify if we need those two efforts to remain separate.

**Comment by Manishearth** [comment]
FWIW unicode-segmentation has been updated to 12 in a pull request, I just am waiting for review.

**Comment by Manishearth** [comment]
Also, unicode-xid is used by the rust compiler and thus maintained quite well. I help maintain the first two, but we could do with more maintainers.

My understanding is that unic-segment is a fork of unicode-segmentation, with the data handling done in a more holistic way

**Comment by zbraniecki** [comment]
This is now covered by https://github.com/unicode-org/icu4x
