### ISSUE TITLE
License

### ISSUE THREAD

**Issue by zbraniecki** [i18n-concept/rust-discuss#10]
It may be quite early to start the conversation, but I prefer to have it early than having to later chase people around.

Most of the intl-related crates in Rust use MIT/Apache dual-license model.

 - ruct_unic - https://github.com/open-i18n/rust-unic
 - intl_pluralrules - https://github.com/zbraniecki/pluralrules/tree/master/intl_pluralrules
 - unicode-rs - https://github.com/unicode-rs
 - unic-locale - https://github.com/zbraniecki/unic-locale

Now, @jfkthame released hyphenation crate which uses MLP-2.0.

I filed https://github.com/jfkthame/mapped_hyph/issues/6 to ask to add MIT/Apache, but I'm also wondering if that combo is reasonable for all stakeholders to move forward with.

**Comment by zbraniecki** [comment]
for fluent the reasoning went into https://github.com/projectfluent/fluent-rs/issues/31

**Comment by Manishearth** [comment]
Note that triple licensing is somewhat frowned upon, so if a crate does MIT/Apache it should probably not _also_ do MPL.

**Comment by jfkthame** [comment]
Seems like for code written by Mozilla employees, at least, this is a discussion that ought to include the licensing team - do you know who should be pulled in?

The [policy](https://www.mozilla.org/en-US/MPL/license-policy/) says "The licensing team recommends MPL 2.0 for client-side code; please consult the team before going against this recommendation", which is what prompted me to use that for mapped_hyph. But personally, at least, I'd have no issue with switching to Apache 2.0 if that's what gets decided.

**Comment by Manishearth** [comment]
From my read of the policy, Apache-2.0 is fine, but  MIT/Apache-2.0 would also be fine, since the patent grant is a restriction placed on contributors, so contributors to an MIT/Apache-2.0 file still must do the patent grant since they're releasing contributions under _both_ licenses.

We should ask the licensing team, though.

**Comment by filmil** [comment]
On Fri, Nov 8, 2019 at 2:11 PM Manish Goregaokar <notifications@github.com>
wrote:

> From my read of the policy, Apache-2.0 is fine, but MIT/Apache-2.0 would
> also be fine, since the patent grant is a restriction placed on
> contributors, so contributors to an MIT/Apache-2.0 file still must do the
> patent grant since they're releasing contributions under *both* licenses.
>
> We should ask the licensing team, though.
>

+1 for Apache-2.0.

F

**Comment by Manishearth** [comment]
Looks like we have a newer, yet-to-be-published license policy, which addresses exactly this case

> … exist as a stand-alone component that can be reused outside Mozilla products they should be licensed under either Apache 2.0, or a dual license that includes Apache 2.0. For example, Rust crates that Firefox depends on are published under an Apache 2.0 / MIT dual license.

So, from the Mozilla side we're good on following the Rust license, though there may be times when the individual author wishes to use MPL instead.

**Comment by jfkthame** [comment]
Well, that certainly seems relevant :) .... where'd you find it?

**Comment by Manishearth** [comment]
Not sure if I can link that yet, but I'll DM you

**Comment by sffc** [comment]
If migrating these to the Unicode Consortium is on our radar, that would mean we should use the [Unicode License](https://www.unicode.org/license.html), a BSD/MIT-like license which is an [approved open-source license](http://lists.opensource.org/pipermail/license-review_lists.opensource.org/2018-September/003504.html).  The SPDX code is [Unicode-DFS-2016](https://spdx.org/licenses/Unicode-DFS-2016.html#licenseText).

**Comment by Manishearth** [comment]
For now I don't think that should be the goal, and as rust crates we should try as much as possible to follow the rust license so that the community can use this best.

**Comment by sffc** [comment]
This was discussed in depth and in ICU4X we settled on the Apache/MIT with an explicit LICENSE file to allow Unicode-licensed code to be integrated and shipped with ICU4X.
