### ISSUE TITLE
UTS 39

### ISSUE THREAD

**Issue by Manishearth** [i18n-concept/rust-discuss#12]
Just opening an issue to let y'all know we're working on [UTS #39 Unicode Security Mechanisms](https://www.unicode.org/reports/tr39) in Rust [here](https://github.com/unicode-rs/unicode-security/issues/3), to be used in the Rust compiler.

(Perhaps we should maintain a list of all Rust projects maintained by members of this group in the readme? Once we start consolidating things it would probably be useful)

**Comment by filmil** [comment]
Happy new year and thanks for letting everyone know. 

As for projects list, feel free to send a pull request over.

**Comment by sffc** [comment]
UTS 39 is discussed in https://github.com/unicode-org/icu4x/issues/42 and https://github.com/unicode-org/icu4x/pull/156, and there is a doc tracking owners of the ecosystem crates here:

https://github.com/unicode-org/icu4x/blob/master/docs/ecosystem.md
