### ISSUE TITLE
Unicode Charter

### ISSUE THREAD

**Issue by sffc** [i18n-concept/rust-discuss#17]
Hi all,

I wrote up an OmnICU Charter for sanctioning under the Unicode Consortium.  Please take a look:

http://bit.ly/omnicu-charter

Please leave comments.  Now is the best time to amend this charter so we can all come into agreement on the goals of an industry project under Unicode.

Regarding this repo: I could either (1) move this repo to unicode-org/omnicu, (2) leave this repo alone indefinitely and make a new repo unicode-org/omnicu, or (3) make a new unicode-org/omnicu and also move this repo into something like unicode-org/rust-discuss.  Thoughts?

**Comment by filmil** [comment]
My vote, in the order of preference

(3) (rust discussion is somewhat separate from omnicu, I think)
(1) (because moving under unicode-org is good)
(2) (rest)

**Comment by zbraniecki** [comment]
Is OmnICU a Rust impl of ICU? Last time we talked the language was undecided, and for me its kinda important :)

My concern is that if OmnICU is a project directed at answering particular needs of Google, then it may want to make different tradeoffs than industry standard. I know that you want to target industry standard, but imagine a case where a benefit of inhouse customer of OmnICU is in conflict in the best decision for the open project. Would you structure OmnICU project to be able to be able to make such decision independent of any single company's needs?

If the answer is no, then I think Google specific project should remain Google specific and an open standard should be developed under Unicode in realm that is independent of single implementater's needs.

**Comment by sffc** [comment]
> Is OmnICU a Rust impl of ICU? Last time we talked the language was undecided, and for me its kinda important :)

That's explained in http://bit.ly/omnicu-charter.  (Please read that first.)

I wrote the charter doc so that when we need to make architectural decisions, we go back and see what is most consistent with the charter.  This is intended to be the solution for "a case where a benefit of inhouse customer of OmnICU is in conflict in the best decision for the open project".  If the charter needs to be changed, the members of the OmnICU TC can vote to amend it.

**Comment by sffc** [comment]
And, to be clear: the reason I want to bring OmnICU into Unicode relatively early in the process is so that we can indeed form an industry-wide TC to solve this problem we all share, which is a small and modular i18n solution for client-side users.  Now is the right time to come to an agreement on the goals of OmnICU and amend the charter according.  Once we have finalized the charter, my hope is that we (Google i18n, Fuchsia, and Mozilla) can combine forces and build something that none of us have the resources to do individually.

**Comment by Manishearth** [comment]
The charter looks good!

I agree with @filmil : A new repo under unicode-org makes sense to me, since this is rust-specific and it's not yet 100% decided if omnICU will be Rust :) But moving this repo under unicode-org with the same name seems fine to me as well.

**Comment by sffc** [comment]
We were approved by the Unicode Offers this morning to be an official SC in Unicode :)

It makes sense to make a new repo for omnicu, and then move this one to unicode-org.  I'll get on that shortly.

**Comment by sffc** [comment]
The repos have been moved as agreed, and the charter has a new permanent home:

https://github.com/unicode-org/omnicu
