### ISSUE TITLE
Mailing List

### ISSUE THREAD

**Issue by sffc** [i18n-concept/rust-discuss#18]
It's good to have a Google Groups mailing list so we can share docs and calendar events and things.  Typically for these things I make an alias in the chromium.org domain.  This doesn't mean we're affiliated with Chromium; it's just the most convenient GSuite account to use since a lot of us already have accounts there, and it's the same GSuite that owns the mailing lists and docs for MFWG and TC39-TG2.

Any concerns with making omnicu-sc@chromium.org?

**Comment by sffc** [comment]
I'm also checking on omnicu-sc@unicode.org; it may or may not be possible to make Google Groups under the unicode.org domain.  If is is possible, then that's preferable over chromium.org.

**Comment by sffc** [comment]
OK, we have a mailing list on the unicode.org domain.  I sent out a few invitations.  Let me know if you want in on that mailing list.

**Comment by alerque** [comment]
I'm very interested in following along and would appreciate an invite. @Manishearth has seen me around ;-) caleb@alerque.com

**Comment by BurntSushi** [comment]
I'd also appreciate following along!

**Comment by sffc** [comment]
Take a look at https://github.com/unicode-org/icu4x :smile: 

I suggest subscribing to that repo and chiming in on open discussions.  You can also take a look at the list of unresolved issues with the "help wanted" label:

https://github.com/unicode-org/icu4x/issues?q=label%3A%22help+wanted%22
