### ISSUE TITLE
Future of intl_pluralrules

### ISSUE THREAD

**Issue by zbraniecki** [i18n-concept/rust-discuss#2]
https://github.com/zbraniecki/pluralrules is currently maintained by me, but I'd prefer to grow the maintainers group.

It's in a good shape, with a helper crates to parse the pluralrules into Rust functions and a script to generate the rust tables based on CLDR JSON data which hopefully makes it easy to maintain and update to latest CLDR at all times.

I'd like to donate the crate to an org which would make it possible for others to update the crate as needed.

**Comment by zbraniecki** [comment]
I added plural rules performance benchmark to https://github.com/zbraniecki/intl-measurements/#current-results-as-of-january-9-2020

The performance is roughly 50 times faster with `intl_pluralrules` than with ICU PluralRules, mostly due to inlining of the plural rules into the code.

**Comment by zbraniecki** [comment]
This means there's a tradeoff, which I'd like to remove with #5 and #4.


I'd like to extend the crate's build system to be able to optionally produce the `rules.rs` file at build time, rather than only as a separate step.
That would fully cover the needs of a setup like Gecko/Firefox where the data could be stored in the source, and updated when needed, and each build would produce the `rules.rs` so the CLDR maintenance wouldn't require any separate steps to update data in plural rules.

This will not cover the needs of dynamic, like what Google needs. For that I want to experiment with ability to use https://github.com/servo/bincode to load binary blobs at runtime and evaluate performance when loading binary data.

**Comment by sffc** [comment]
This is on track for ICU4X: https://github.com/unicode-org/icu4x/issues/116
