### ISSUE TITLE
Future of unic-locale

### ISSUE THREAD

**Issue by zbraniecki** [i18n-concept/rust-discuss#3]
https://github.com/zbraniecki/unic-locale contains two crates - `unic-langid` and `unic-locale`. The former separates out Unicode LanguageIdentifier parsing/modifying/serializing and the latter adds Unicode Extensions.

The former is quite feature complete on the `well-formed` level, with optional features such as likely subtags and layout information (character orientation - LTR/RTL) and scripts to easily update the data to latest CLDR as needed.

I'd like to donate the crates to an org that will distribute the maintenance and reduce the bus factor.

**Comment by zbraniecki** [comment]
Hi all!

I just pushed an update of `unic-langid` and `unic-locale` to 0.7.

The changes in `unic-langid` are fairly small, but I hope that separating out `clear_*` from `set_*` makes the API cleaner and more canonical (clear_* is infallible).

The changes to `unic-locale` are much bigger. Thanks to @hjmallon contributions we now have quite complete support for extensions manipulation and better conformance (sorting, dedup etc.).

We also got nice boosts to performance, in range of 8-30% thanks to better parsing iteration over `&[u8]` which allows us to avoid unicode validation to `&str` since TinyStr is doing its own validation to ASCII anyway.

CTA: I'd like to ask you to look at the docs, both for https://docs.rs/unic-langid/0.7.0/unic_langid/ and https://docs.rs/unic-locale/0.7.0/unic_locale/ and verify that the API for `LanguageIdentifier` and `Locale` looks reasonable from the Unicode/ICU standpoint.
I feel like we're getting close to stability, and I'm about to [replace Locale parsing](https://bugzilla.mozilla.org/show_bug.cgi?id=1571915) in Gecko with `unic-langid`, but I'd prefer to get more production experience and domain expertise before I claim `1.0`.

**Comment by sffc** [comment]
@FrankYFTang, are you interested in looking at @zbraniecki's Rust locale-related classes linked above?

**Comment by hjmallon** [comment]
@zbraniecki the link 'replace Locale parsing' is pointing to the wrong place I think?

**Comment by zbraniecki** [comment]
yup! fixed, thank you!

**Comment by zbraniecki** [comment]
I also collected basic measurements of ICU vs `unic-langid` - https://github.com/zbraniecki/intl-measurements/blob/master/README.md#current-results-as-of-oct-30-2019

I'd appreciate a review of my ICU use by someone with more experience in ICU4C.

**Comment by sffc** [comment]
I finally got a chance to take a look.  Looks quite cool!  The API is conventional Rust and appears to have full coverage of 402.

Do you want to use `.maximize()` and `.minimize()` for the likely subtags functions to match 402?

I ran your benchmarks and posted my results in https://github.com/zbraniecki/intl-measurements/issues/2.

**Comment by zbraniecki** [comment]
> Do you want to use .maximize() and .minimize() for the likely subtags functions to match 402?

I'm torn on that. I feel like `maximize` and `minimize` is a bit more, pardon my french, dumbed down naming scheme. But I'm not strongly opposed, and we have time until 1.0 to make such decisions!

If you believe that this is a better naming convention, I'll switch!

**Comment by sffc** [comment]
Spun off the discussion regarding the naming of the likely subtags methods.

**Comment by zbraniecki** [comment]
I updated the performance and memory measurements to closer match ICU vs unic_langid - https://github.com/zbraniecki/intl-measurements/#current-results-as-of-january-9-2020

The results remain the same.

**Comment by sffc** [comment]
This is now part of ICU4X: https://github.com/unicode-org/icu4x/issues/31
