### ISSUE TITLE
ECMA-402 support in Rust

### ISSUE THREAD

**Issue by filmil** [i18n-concept/rust-discuss#7]
I think there is value for supporting well thought-out I18N APIs in Rust as well as in other languages.  This is because no single person can be an all-around expert on all matters I18N just by the nature of the subject, and we should be well served if we all work together to minimize the amount of wheel reinvention.  ECMA-402 in particular has had tremendous amount of work invested in it, and seems like a well understood basis for this work.

A few topics that seem of interest in the Rust world as of today:
- ECMA 402 compatible implementation for Rust
- ECMA 402 compatible API definition, to enable multiple implementations of ECMA 402 to exist if needed: not all requirements are equally valid in all contexts.
- Conformance tests, to ensure implementations are mutually compatible
- A way for Rust to contribute language-neutral proposals to ECMA 402 in case we would like to propose additional functionality.

**Comment by filmil** [comment]
For reference, see the "still missing" bit in https://www.arewewebyet.org/topics/i18n/

**Comment by filmil** [comment]
For even more reference: https://github.com/tc39/ecma402

**Comment by zbraniecki** [comment]
I think it should be fairly easy to create a ECMA402-like API that uses lower level crates that provide a more complete ICU-like functionality.

The end result would be that users can chose the Level of Detail:

 - "I just need good basic intl" - use ecma402-api
 - "I need more complex API" - use icu-api
 - "I need a granular selection of APIs" - use "i18n-concept-datetimeformat", "i18n-concept-collator" etc.

**Comment by filmil** [comment]
> "I need more complex API" - use icu-api

As you may have noticed, I filed issue #8 for this bit.  Also I think `s/complex API/complex functionality/` above.

**Comment by sffc** [comment]
Regarding the last bullet,

> A way for Rust to contribute language-neutral proposals to ECMA 402 in case we would like to propose additional functionality.

Let's cross that bridge on an as-needed basis.  I think it would be reasonable for Rust to propose and implement a design that is consistent with the ECMA-402 design, such that it could be upstreamed at some point in the future.  This is where it's important to maintain solid communication channels.

**Comment by filmil** [comment]
> Let's cross that bridge on an as-needed basis. 

@sffc Glad to defer this for as long as needed.  I was mostly thinking about `MessageFormat` which is not in ECMA-402, but which we may soon get to.

**Comment by filmil** [comment]
There is now https://github.com/google/rust_icu/projects/1 for ICU in particular.  With that I believe this is OK to close, and followup discussions can happen as needed.
