### ISSUE TITLE
ICU functionality support in Rust

### ISSUE THREAD

**Issue by filmil** [i18n-concept/rust-discuss#8]
This is similar to issue #7 in that it's calling for support for a well understood library in Rust.

Also mentioned in https://www.arewewebyet.org/topics/i18n/

Full disclosure, my project (Fuchsia OS) needs ICU *today*, so we started by [wrapping ICU4C](https://fuchsia.googlesource.com/fuchsia/+/refs/heads/master/src/lib/icu/), learning from other work in this space.  See references below for details.

It's hard to do justice to all the references to prior art, but I'll try, and will try to backfill with more information where possible.

Bindings
- https://github.com/servo/rust-icu
- https://github.com/fullcontact/icu-sys

Related issues
- https://github.com/rust-lang/rust/issues/14656
- https://github.com/rust-lang/rfcs/issues/797

**Comment by filmil** [comment]
@zbraniecki @sffc 
You may want to check this out: https://github.com/google/rust_icu
Cheers!

**Comment by sffc** [comment]
Cool, that was quick!  Glad you got it approved.  I will now look through the wrappers you've made and open issues on the new repo with suggestions.

**Comment by filmil** [comment]
Thanks that will be great!

**Comment by filmil** [comment]
In the meantime two major developments happened:

1. We started https://github.com/unicode-org/icu4x
2. We have https://github.com/google/rust_icu

With these two in existence I think this particular issue (which is, Unicode-on-rust getting more traction) has been handled.

Closing.
